version: "3.7"

services:
  redis:
    image: redis:latest
  web:
    build:
      context: .
      dockerfile: .devcontainer/app/base.Dockerfile
    ports:
      - "8000:8000"
    links:
      - redis
    command: "/app/.devcontainer/app/idle.sh"